service: starwars-api-serverless

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:us-east-1:*:table/StarWarsTable

functions:
  getAllStarWarsData:
    handler: src/handlers/getAllStarWarsData.handler
    timeout: 30
    events:
      - http:
          path: starwarsapi/all
          method: get

  getStarWarsDataById:
    handler: src/handlers/getStarWarsDataById.handler
    timeout: 30
    events:
      - http:
          path: starwarsapi/{id}
          method: get

  postStarWarsData:
    handler: src/handlers/postStarWarsData.handler
    timeout: 30
    events:
      - http:
          path: starwarsapi
          method: post

resources:
  Resources:
    StarWarsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: StarWarsTable
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
